extends:
  - 'standard-with-typescript'
  - 'prettier'

parserOptions:
  project: './tsconfig.json'

rules:
  'no-case-declarations': 'off'
  'array-callback-return': 'off'
  'no-multi-str': 'off'
  'no-useless-escape': 'off'
  'node/no-deprecated-api': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-misused-promises': 'off'
  '@typescript-eslint/no-extraneous-class': 'off'
  '@typescript-eslint/prefer-optional-chain': 'off'
  '@typescript-eslint/prefer-nullish-coalescing': 'off'
  '@typescript-eslint/restrict-template-expressions': 'off'
  '@typescript-eslint/restrict-plus-operands': 'off'
  '@typescript-eslint/strict-boolean-expressions': 'off'

overrides:
  ###
  # Test file overrides
  ###
  - files: ['**/*.test.ts']
    env:
      jest: true
