changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

packageExtensions:
  readable-stream@*:
    dependencies:
      events: "*"
  stream-browserify@*:
    dependencies:
      events: "*"
  eslint-module-utils@*:
    dependencies:
      eslint: "*"
      eslint-import-resolver-node: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
