packageExtensions:
  readable-stream@*:
    dependencies:
      events: "*"
  stream-browserify@*:
    dependencies:
      events: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.cjs
