nmMode: hardlinks-local
nodeLinker: node-modules
nmHoistingLimits: workspaces

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint: '*'
      eslint-import-resolver-node: '*'
  readable-stream@*:
    dependencies:
      events: '*'
  stream-browserify@*:
    dependencies:
      events: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.1.1.cjs

supportedArchitectures:
  os:
    - 'darwin'
    - 'linux'
  cpu:
    - 'x64'
    - 'arm64'
