enableScripts: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmAuthToken: "${NPM_AUTH_TOKEN-undefined}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.8.1.cjs

# this allows `yarn version` to run on shallow checkout (e.g. publish workflow)
changesetBaseRefs: ["HEAD"]
