name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12', '13']
    services:
      rtsp:
        image: steabert/gst-rtsp-launch
        ports:
        - 8554:8554
    steps:
    - uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Linting & Unit testing
      run: |
        yarn lint
        yarn test
    - name: Build
      run: yarn build
    - name: Test basic video functionality
      run: |
        node rtsp-ws-server/tcp-ws-proxy.js >& tcp-ws-proxy.log &
        yarn http-server examples/browser >& http-server.log &
        yarn cypress run
    - name: Release
      id: release
      if: startsWith(github.ref, 'refs/tags/v') && matrix.node-version == '12'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # provided by Actions
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/v') && matrix.node-version == '12'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: dist/media-stream-library.min.js
        asset_name: media-stream-library.min.js
        asset_content_type: application/javascript
    - name: Deploy NPM package
      if: startsWith(github.ref, 'refs/tags/v') && matrix.node-version == '12'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        if [[ $GITHUB_REF =~ alpha|beta ]]; then
            npm publish --tag next
        else
            npm publish --tag latest
        fi
